# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
code_generation:
  docstrings:
    language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: "Do not add colors to mermaid diagrams. Use Class diagrams."
  poem: false
  auto_review:
    enabled: true
    drafts: true
  path_filters:
    - "**/*.shader"
    - "**/*.hlsl"
    - "**/*.cs"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"
    - "**/*.sh"
    - "**/*.command"
    - "**/*.md"
    - "**/*.uss"
    - "**/*.uxml"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
chat:
  auto_reply: true