/**
 * Auto-generates bundled-skills.ts from skill-definitions directory.
 * Scans all SKILL.md files and generates import statements and BUNDLED_SKILLS array.
 * Skills with `internal: true` in frontmatter are excluded from generation.
 *
 * Usage: npx tsx scripts/generate-bundled-skills.ts
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SKILL_DEFINITIONS_DIR = join(__dirname, '../src/skills/skill-definitions');
const OUTPUT_FILE = join(__dirname, '../src/skills/bundled-skills.ts');

interface SkillMetadata {
  dirName: string;
  name: string;
  isInternal: boolean;
}

function parseFrontmatter(content: string): Record<string, string | boolean> {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) {
    return {};
  }

  const frontmatter: Record<string, string | boolean> = {};
  const lines = frontmatterMatch[1].split('\n');

  for (const line of lines) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) {
      continue;
    }

    const key = line.slice(0, colonIndex).trim();
    const value = line.slice(colonIndex + 1).trim();

    if (value === 'true') {
      frontmatter[key] = true;
    } else if (value === 'false') {
      frontmatter[key] = false;
    } else {
      frontmatter[key] = value;
    }
  }

  return frontmatter;
}

function getSkillMetadata(dirName: string): SkillMetadata | null {
  const skillPath = join(SKILL_DEFINITIONS_DIR, dirName, 'SKILL.md');

  if (!existsSync(skillPath)) {
    return null;
  }

  const content = readFileSync(skillPath, 'utf-8');
  const frontmatter = parseFrontmatter(content);

  const name = typeof frontmatter.name === 'string' ? frontmatter.name : dirName;
  const isInternal = frontmatter.internal === true;

  return { dirName, name, isInternal };
}

function toVariableName(dirName: string): string {
  return dirName
    .replace(/^uloop-/, '')
    .replace(/-([a-z])/g, (_, char) => char.toUpperCase())
    .concat('Skill');
}

function generateBundledSkillsFile(skills: SkillMetadata[]): string {
  const imports = skills
    .map((skill) => {
      const varName = toVariableName(skill.dirName);
      return `import ${varName} from './skill-definitions/${skill.dirName}/SKILL.md';`;
    })
    .join('\n');

  const entries = skills
    .map((skill) => {
      const varName = toVariableName(skill.dirName);
      return `  {
    name: '${skill.name}',
    dirName: '${skill.dirName}',
    content: ${varName},
  },`;
    })
    .join('\n');

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-bundled-skills.ts
 *
 * This file is automatically generated from skill-definitions directory.
 * To add a new skill, create a new directory in skill-definitions with a SKILL.md file.
 * To exclude a skill from bundling, add \`internal: true\` to its frontmatter.
 */

${imports}

export interface BundledSkill {
  name: string;
  dirName: string;
  content: string;
}

export const BUNDLED_SKILLS: BundledSkill[] = [
${entries}
];

export function getBundledSkillByName(name: string): BundledSkill | undefined {
  return BUNDLED_SKILLS.find((skill) => skill.name === name);
}
`;
}

function main(): void {
  const dirs = readdirSync(SKILL_DEFINITIONS_DIR, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name)
    .sort();

  const allSkills: SkillMetadata[] = [];
  const internalSkills: string[] = [];

  for (const dirName of dirs) {
    const metadata = getSkillMetadata(dirName);
    if (metadata === null) {
      console.warn(`Warning: No SKILL.md found in ${dirName}, skipping`);
      continue;
    }

    if (metadata.isInternal) {
      internalSkills.push(metadata.name);
      continue;
    }

    allSkills.push(metadata);
  }

  const output = generateBundledSkillsFile(allSkills);
  writeFileSync(OUTPUT_FILE, output, 'utf-8');

  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`  - Included: ${allSkills.length} skills`);
  if (internalSkills.length > 0) {
    console.log(`  - Excluded (internal): ${internalSkills.join(', ')}`);
  }
}

main();

