/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-bundled-skills.ts
 *
 * This file is automatically generated from:
 *   - Editor/Api/McpTools/<ToolFolder>/SKILL.md
 *   - skill-definitions/cli-only/<SkillFolder>/SKILL.md
 *
 * To add a new skill, create a SKILL.md file in the appropriate location.
 * To exclude a skill from bundling, add `internal: true` to its frontmatter.
 */

import captureUnityWindowSkill from '../../../Editor/Api/McpTools/CaptureUnityWindow/SKILL.md';
import clearConsoleSkill from '../../../Editor/Api/McpTools/ClearConsole/SKILL.md';
import compileSkill from '../../../Editor/Api/McpTools/Compile/SKILL.md';
import controlPlayModeSkill from '../../../Editor/Api/McpTools/ControlPlayMode/SKILL.md';
import executeDynamicCodeSkill from '../../../Editor/Api/McpTools/ExecuteDynamicCode/SKILL.md';
import executeMenuItemSkill from '../../../Editor/Api/McpTools/ExecuteMenuItem/SKILL.md';
import findGameObjectsSkill from '../../../Editor/Api/McpTools/FindGameObjects/SKILL.md';
import focusWindowSkill from '../../../Editor/Api/McpTools/FocusUnityWindow/SKILL.md';
import getHierarchySkill from '../../../Editor/Api/McpTools/GetHierarchy/SKILL.md';
import getLogsSkill from '../../../Editor/Api/McpTools/GetLogs/SKILL.md';
import getMenuItemsSkill from '../../../Editor/Api/McpTools/GetMenuItems/SKILL.md';
import getProviderDetailsSkill from '../../../Editor/Api/McpTools/UnitySearchProviderDetails/SKILL.md';
import runTestsSkill from '../../../Editor/Api/McpTools/RunTests/SKILL.md';
import unitySearchSkill from '../../../Editor/Api/McpTools/UnitySearch/SKILL.md';

export interface BundledSkill {
  name: string;
  dirName: string;
  content: string;
}

export const BUNDLED_SKILLS: BundledSkill[] = [
  {
    name: 'uloop-capture-unity-window',
    dirName: 'uloop-capture-unity-window',
    content: captureUnityWindowSkill,
  },
  {
    name: 'uloop-clear-console',
    dirName: 'uloop-clear-console',
    content: clearConsoleSkill,
  },
  {
    name: 'uloop-compile',
    dirName: 'uloop-compile',
    content: compileSkill,
  },
  {
    name: 'uloop-control-play-mode',
    dirName: 'uloop-control-play-mode',
    content: controlPlayModeSkill,
  },
  {
    name: 'uloop-execute-dynamic-code',
    dirName: 'uloop-execute-dynamic-code',
    content: executeDynamicCodeSkill,
  },
  {
    name: 'uloop-execute-menu-item',
    dirName: 'uloop-execute-menu-item',
    content: executeMenuItemSkill,
  },
  {
    name: 'uloop-find-game-objects',
    dirName: 'uloop-find-game-objects',
    content: findGameObjectsSkill,
  },
  {
    name: 'uloop-focus-window',
    dirName: 'uloop-focus-window',
    content: focusWindowSkill,
  },
  {
    name: 'uloop-get-hierarchy',
    dirName: 'uloop-get-hierarchy',
    content: getHierarchySkill,
  },
  {
    name: 'uloop-get-logs',
    dirName: 'uloop-get-logs',
    content: getLogsSkill,
  },
  {
    name: 'uloop-get-menu-items',
    dirName: 'uloop-get-menu-items',
    content: getMenuItemsSkill,
  },
  {
    name: 'uloop-get-provider-details',
    dirName: 'uloop-get-provider-details',
    content: getProviderDetailsSkill,
  },
  {
    name: 'uloop-run-tests',
    dirName: 'uloop-run-tests',
    content: runTestsSkill,
  },
  {
    name: 'uloop-unity-search',
    dirName: 'uloop-unity-search',
    content: unitySearchSkill,
  },
];

export function getBundledSkillByName(name: string): BundledSkill | undefined {
  return BUNDLED_SKILLS.find((skill) => skill.name === name);
}
