/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-bundled-skills.ts
 *
 * This file is automatically generated from:
 *   - Editor/Api/McpTools/*/SKILL.md (C# tool folders)
 *   - skill-definitions/cli-only/*/SKILL.md (CLI-only skills)
 *
 * To add a new skill, create a SKILL.md file in the appropriate location.
 * To exclude a skill from bundling, add `internal: true` to its frontmatter.
 */

import CaptureUnityWindowSkill from '../../../Editor/Api/McpTools/CaptureUnityWindow/SKILL.md';
import ClearConsoleSkill from '../../../Editor/Api/McpTools/ClearConsole/SKILL.md';
import CompileSkill from '../../../Editor/Api/McpTools/Compile/SKILL.md';
import ControlPlayModeSkill from '../../../Editor/Api/McpTools/ControlPlayMode/SKILL.md';
import ExecuteDynamicCodeSkill from '../../../Editor/Api/McpTools/ExecuteDynamicCode/SKILL.md';
import ExecuteMenuItemSkill from '../../../Editor/Api/McpTools/ExecuteMenuItem/SKILL.md';
import FindGameObjectsSkill from '../../../Editor/Api/McpTools/FindGameObjects/SKILL.md';
import FocusUnityWindowSkill from '../../../Editor/Api/McpTools/FocusUnityWindow/SKILL.md';
import GetHierarchySkill from '../../../Editor/Api/McpTools/GetHierarchy/SKILL.md';
import GetLogsSkill from '../../../Editor/Api/McpTools/GetLogs/SKILL.md';
import GetMenuItemsSkill from '../../../Editor/Api/McpTools/GetMenuItems/SKILL.md';
import UnitySearchProviderDetailsSkill from '../../../Editor/Api/McpTools/UnitySearchProviderDetails/SKILL.md';
import RunTestsSkill from '../../../Editor/Api/McpTools/RunTests/SKILL.md';
import UnitySearchSkill from '../../../Editor/Api/McpTools/UnitySearch/SKILL.md';

export interface BundledSkill {
  name: string;
  dirName: string;
  content: string;
}

export const BUNDLED_SKILLS: BundledSkill[] = [
  {
    name: 'uloop-capture-unity-window',
    dirName: 'CaptureUnityWindow',
    content: CaptureUnityWindowSkill,
  },
  {
    name: 'uloop-clear-console',
    dirName: 'ClearConsole',
    content: ClearConsoleSkill,
  },
  {
    name: 'uloop-compile',
    dirName: 'Compile',
    content: CompileSkill,
  },
  {
    name: 'uloop-control-play-mode',
    dirName: 'ControlPlayMode',
    content: ControlPlayModeSkill,
  },
  {
    name: 'uloop-execute-dynamic-code',
    dirName: 'ExecuteDynamicCode',
    content: ExecuteDynamicCodeSkill,
  },
  {
    name: 'uloop-execute-menu-item',
    dirName: 'ExecuteMenuItem',
    content: ExecuteMenuItemSkill,
  },
  {
    name: 'uloop-find-game-objects',
    dirName: 'FindGameObjects',
    content: FindGameObjectsSkill,
  },
  {
    name: 'uloop-focus-window',
    dirName: 'FocusUnityWindow',
    content: FocusUnityWindowSkill,
  },
  {
    name: 'uloop-get-hierarchy',
    dirName: 'GetHierarchy',
    content: GetHierarchySkill,
  },
  {
    name: 'uloop-get-logs',
    dirName: 'GetLogs',
    content: GetLogsSkill,
  },
  {
    name: 'uloop-get-menu-items',
    dirName: 'GetMenuItems',
    content: GetMenuItemsSkill,
  },
  {
    name: 'uloop-get-provider-details',
    dirName: 'UnitySearchProviderDetails',
    content: UnitySearchProviderDetailsSkill,
  },
  {
    name: 'uloop-run-tests',
    dirName: 'RunTests',
    content: RunTestsSkill,
  },
  {
    name: 'uloop-unity-search',
    dirName: 'UnitySearch',
    content: UnitySearchSkill,
  },
];

export function getBundledSkillByName(name: string): BundledSkill | undefined {
  return BUNDLED_SKILLS.find((skill) => skill.name === name);
}
