#!/usr/bin/env sh

changed_server_ts="$(git diff --cached --name-only --diff-filter=ACM | grep -E '^Packages/src/TypeScriptServer~/src/.*\.(ts|tsx)$' || true)"
changed_cli_ts="$(git diff --cached --name-only --diff-filter=ACM | grep -E '^Packages/src/Cli~/src/.*\.(ts|tsx)$' || true)"

cd Packages/src/TypeScriptServer~
npx lint-staged

if [ -n "$changed_server_ts" ]; then
  npx tsc --noEmit
  npx knip
fi

cd ../Cli~

if [ -n "$changed_cli_ts" ]; then
  npx knip
fi