name: publish-on-release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Passed to npm-publish workflow for OIDC trusted publishing

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'v')
    uses: ./.github/workflows/npm-publish.yml
    with:
      ref: ${{ github.event.release.tag_name }}
      dry-run: false
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: read
      id-token: write
